* Usage
  Call the =easy-convert-interactive= command to convert units from
  the minibuffer.

  For example:
  : Old value and unit (type C-z for unit list) : 100oz
 
  : to unit (type C-z for unit list) : g

  : 100oz converted to g = 2834.9523125 g

  This program is built on top of calc-units, which means it
  understands the usual prefixes, such as k (kilo), m (milli), y
  (yocto)...

  : Old value and unit (type C-z for unit list) : kg
 
  : to unit (type C-z for unit list) : g

  : kg converted to g = 1000 g

* Installation
  
  : (add-to-list 'load-path "<easy-convert-installation-path>")
  
  : (require 'easy-convert)

  Optionally, you can bind it to a key sequence:

  : (global-set-key (kbd "C-c u") (quote easy-convert-interactive))

* License
  
  Copyright 2012 Free Software Foundation, Inc.
  
  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
